const cereals = [
  {
    name: "Apple Cinnamon Cheerios",
    image: "/images/apple_cinnamon_cheerios.jpg",
    brand: "General Mills",
    price: 3.49,
    rating: "4",
  },
  {
    name: "Cap'n Crunch",
    image: "/images/capn_crunch.jpg",
    brand: "Quaker Oats",
    price: 3.99,
    rating: "2",
  },
  {
    name: "Cap'n Crunch Berries",
    image: "/images/capn_crunch_berries.jpg",
    brand: "Quaker Oats",
    price: 4.49,
    rating: "3",
  },
  {
    name: "Cap'n Crunch Oops Berries",
    image: "/images/capn_crunch_oops_all_berries.jpg",
    brand: "Quaker Oats",
    price: 3.99,
    rating: "1",
  },
  {
    name: "Cheerios",
    image: "/images/cheerios.jpg",
    brand: "General Mills",
    price: 3.99,
    rating: "5",
  },
  {
    name: "Chocolate Cheerios",
    image: "/images/chocolate_cheerios.jpg",
    brand: "General Mills",
    price: 3.99,
    rating: "4",
  },
  {
    name: "Chocolate Chex",
    image: "/images/chocolate_chex.jpg",
    brand: "General Mills",
    price: 3.99,
    rating: "3",
  },
  {
    name: "Cinnamon Toast Crunch",
    image: "/images/cinnamon_toast_crunch.jpg",
    brand: "General Mills",
    price: 3.49,
    rating: "4",
  },
  {
    name: "Cinnamon Toast Crunch Churros",
    image: "/images/cinnamon_toast_crunch_churros.jpg",
    brand: "General Mills",
    price: 3.49,
    rating: "5",
  },
  {
    name: "Cocoa Pebbles",
    image: "/images/cocoa_pebbles.jpg",
    brand: "Post",
    price: 3.99,
    rating: "3",
  },
  {
    name: "Cookie Crisp",
    image: "/images/cookie_crisp.jpg",
    brand: "General Mills",
    price: 4.49,
    rating: "4",
  },
  {
    name: "Corn Chex",
    image: "/images/corn_chex.jpg",
    brand: "General Mills",
    price: 3.99,
    rating: "3",
  },
  {
    name: "Corn Flakes",
    image: "/images/corn_flakes.jpg",
    brand: "Kellogs",
    price: 3.99,
    rating: "5",
  },
  {
    name: "Frosted Flakes",
    image: "/images/frosted_flakes.jpg",
    brand: "Kellogs",
    price: 3.99,
    rating: "4",
  },
  {
    name: "Frosted Mini Wheats",
    image: "/images/frosted_mini_wheats.jpg",
    brand: "Kellogs",
    price: 3.99,
    rating: "4",
  },
  {
    name: "Fruit Loops",
    image: "/images/fruit_loops.jpg",
    brand: "Kellogs",
    price: 3.99,
    rating: "3",
  },
  {
    name: "Fruity Pebbles",
    image: "/images/fruity_pebbles.jpg",
    brand: "Post",
    price: 3.49,
    rating: "2",
  },
  {
    name: "Golden Grahams",
    image: "/images/golden_grahams.jpg",
    brand: "General Mills",
    price: 4.49,
    rating: "1",
  },
  {
    name: "Grape Nuts",
    image: "/images/grape_nuts.jpg",
    brand: "Post",
    price: 3.99,
    rating: "5",
  },
  { 
    name: "Great Grains Raisins, Dates, & Pecans",
    image: "/images/great_grains_raisins_dates_pecans.jpg",
    brand: "Post",
    price: 3.99,
    rating: "5",
  },
  {
    name: "Honey Bunches of Oats",
    image: "/images/honey_bunches_of_oats.jpg",
    brand: "Post",
    price: 3.99,
    rating: "3",
  },
  {
    name: "Kix",
    image: "/images/kix.jpg",
    brand: "General Mills",
    price: 4.49,
    rating: "4",
  },
  {
    name: "Koshi Go",
    image: "/images/koshi_go.jpg",
    brand: "Kellogs",
    price: 3.99,
    rating: "1",
  },
  {
    name: "Life",
    image: "/images/life.jpg",
    brand: "Quaker Oats",
    price: 3.99,
    rating: "3",
  },
  {
    name: "Lucky Charms",
    image: "/images/lucky_charms.jpg",
    brand: "General Mills",
    price: 3.99,
    rating: "4",
  },
  {
    name: "Quaker Oatmeal Squares",
    image: "/images/quaker_oatmeal_squares.jpg",
    brand: "Quaker Oats",
    price: 4.49,
    rating: "2",
  },
  {
    name: "Raisin Bran",
    image: "/images/raisin_bran.jpg",
    brand: "Kellogs",
    price: 3.49,
    rating: "3",
  },
  {
    name: "Raisin Bran Crunch",
    image: "/images/raisin_bran_crunch.jpg",
    brand: "Kellogs",
    rating: "4",
    price: 3.99,
  },
  {
    name: "Rice Chex",
    image: "/images/rice_chex.jpg",
    brand: "General Mills",
    price: 3.99,
    rating: "4",
  },
  {
    name: "Shredded Wheat",
    image: "/images/shredded_wheat.jpg",
    brand: "Post",
    price: 3.49,
    rating: "2",
  },
  {
    name: "Special K",
    image: "/images/special_k.jpg",
    brand: "Kellogs",
    price: 3.99,
    rating: "5",
  },
  {
    name: "Total",
    image: "/images/total.jpg",
    brand: "General Mills",
    price: 3.99,
    rating: "4",
  },
  {
    name: "Trix",
    image: "/images/trix.jpg",
    brand: "General Mills",
    price: 3.99,
    rating: "2",
  },
  {
    name: "Very Berry Cheerios",
    image: "/images/very_berry_cheerios.jpg",
    brand: "General Mills",
    price: 3.99,
    rating: "3",
  },
  {
    name: "Wheat Chex",
    image: "/images/wheat_chex.jpg",
    brand: "General Mills",
    price: 3.49,
    rating: "5",
  },
  {
    name: "Wheaties",
    image: "/images/wheaties.jpg",
    brand: "General Mills",
    price: 4.49,
    rating: "4",
  },
]

export default cereals;
